services:
  xion:
    image: ghcr.io/burnt-labs/xion/xion:${XION_VERSION:-latest}
    command: >
      /usr/bin/cosmovisor run start \
        --api.address tcp://0.0.0.0:1317 \
        --api.enable true \
        --api.enabled-unsafe-cors true \
        --api.swagger true \
        --grpc.enable true \
        --grpc.address 0.0.0.0:9090 \
        --grpc-web.enable \
        --minimum-gas-prices 0.025uxion \
        --rpc.laddr tcp://0.0.0.0:26657
    entrypoint: /home/xiond/init/entrypoint.sh
    deploy:
      replicas: ${NUM_VALIDATORS:-3}
    environment:
      CHAIN_ID: ${CHAIN_ID}
      DAEMON_HOME: ${DAEMON_HOME}
      DAEMON_NAME: ${DAEMON_NAME}
      DEFAULT_DENOM: ${DEFAULT_DENOM}
      DENOM_METADATA_NAME: ${DENOM_METADATA_NAME}
      GENESIS_AMOUNT: ${GENESIS_AMOUNT}
      GENTX_AMOUNT: ${GENTX_AMOUNT}
      MNEMONIC: ${MNEMONIC}
      MODIFY_GENESIS_JQ: ${MODIFY_GENESIS_JQ}
      NUM_VALIDATORS: ${NUM_VALIDATORS:-3}
      SOURCE_CHAIN_ID: ${SOURCE_CHAIN_ID:-""}
      SOURCE_CHAIN_RPC: ${SOURCE_CHAIN_RPC:-""}
      SOURCE_CHAIN_CODE_IDS: ${SOURCE_CHAIN_CODE_IDS:-()}
    ports:
      - 1317
      - 26656
      - 26657
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:26657/status"]
      interval: 5s
      timeout: 5s
      retries: 5
    user: root
    working_dir: /home/${DAEMON_NAME}
    networks:
      - default
    volumes:
      - /home/${DAEMON_NAME}
      - shared:/home/${DAEMON_NAME}/.shared
      - ./scripts/init:/home/${DAEMON_NAME}/init

  xion-dashboard:
    build:
      context: xion-dashboard-app/
      args:
        ENV_FILE: .env.example
    ports:
      - "4173:4173"
    user: root
    networks:
      - default

  xion-developer-portal:
    build:
      context: xion-developer-portal/
      args:
        ENV_FILE: .env.example
    ports:
      - "5000:3000"
    user: root
    networks:
      - default

  xion-explorer:
    build:
      context: xion-explorer/
    ports:
      - "3000:3000"
    user: root
    networks:
      - default

  xion-staking:
    build:
      context: ./xion-staking
    ports:
      - 4000:4000
    environment:
      SAMPLE: sample

  xion-aa-api:
    build:
      context: ./xion-aa-api
    environment:
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
      AWS_REGION: "us-east-1"
    ports:
      - "8787:8787"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/healthz/readiness"]

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4571:4571"            # LocalStack SQS port (optional)
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=sqs,secretsmanager  # Specify the services you want to run (e.g., SQS)
      - DEBUG=1                # Enable debug logging (optional)
      - AWS_ACCESS_KEY_ID=test  # Default AWS credentials
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    volumes: # NOTICE: make sure that the file is executable [chmod +x scripts/init/init-aws-localstack.sh]
      - "./scripts/init/init-aws-localstack.sh:/etc/localstack/init/ready.d/init-aws.sh"
      - "./scripts/init/init-aws-secrets.json:/secrets.json"

networks:
  default:

volumes:
  shared:
